name: Off-by-One
markdown: redcarpet
safe: true
lsi: false
pygments: true
url: http://off-by-one-mag.github.io/issue-1
permalink: :title/

prose:
    metadata:
        _posts:
            - name: "layout"
              field: 
                  element: "hidden"
                  value: "post"
            - name: "title"
              field:
                  element: "text"
                  label: "Title"
#    siteurl: http://off-by-one-mag.github.io/issue-1/
