name: Off-by-One
markdown: redcarpet
safe: true
lsi: false
pygments: true
url: http://off-by-one-mag.github.io/issue-1

prose:
  metadata:
    _posts:
      - name: "permalink"
        field:
          element: "hidden"
          value: ":title/"
#    siteurl: http://off-by-one-mag.github.io/issue-1/